CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100),
	email VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	title VARCHAR(512) NOT NULL,
	post_type VARCHAR(20) NOT NULL,
	slug VARCHAR(256) NOT NULL UNIQUE,
	status VARCHAR(20) NOT NULL,
	content TEXT,
	featured_image_url VARCHAR(1024),
	publish_on TIMESTAMP NOT NULL
);